# Generated by Django 5.2.17 on 2026-09-22 06:59

import apps.vets.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0002_seed_specializations'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetprofile',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='vet_licenses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), apps.vets.models.validate_document_size], verbose_name='Diplom / litsenziya'),
        ),
    ]
