# Generated by Django 5.2.17 on 2026-09-29 10:17

import apps.vets.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0003_vetprofile_license_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinics/', verbose_name='Logotip / rasm')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Telefon')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('services', models.TextField(blank=True, verbose_name='Xizmatlar')),
                ('working_hours', models.CharField(blank=True, max_length=120, verbose_name='Ish vaqti')),
                ('is_24h', models.BooleanField(default=False, verbose_name='24/7 ishlaydi')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Viloyat')),
                ('district', models.CharField(blank=True, max_length=80, verbose_name='Tuman')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Kenglik')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Uzunlik')),
                ('license_document', models.FileField(blank=True, null=True, upload_to='clinic_licenses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), apps.vets.models.validate_document_size], verbose_name='Litsenziya')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('specializations', models.ManyToManyField(blank=True, related_name='clinics', to='vets.specialization')),
            ],
            options={
                'verbose_name': 'Klinika',
                'verbose_name_plural': 'Klinikalar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vets', to='vets.clinic', verbose_name='Klinika'),
        ),
    ]
