# Generated by Django 5.0.6 on 2026-05-31 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('call_new', 'Yangi chaqiruv'), ('call_status', "Chaqiruv holati o'zgardi"), ('tender_new', 'Yangi tender'), ('offer_new', 'Yangi taklif'), ('offer_accepted', 'Taklif qabul qilindi'), ('offer_declined', 'Taklif rad etildi')], max_length=20, verbose_name='Turi')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Sarlavha')),
                ('body', models.TextField(blank=True, verbose_name='Matn')),
                ('bot', models.CharField(default='client', max_length=10, verbose_name='Bot')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('is_sent', models.BooleanField(default=False, verbose_name='Yuborilgan')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan vaqt')),
                ('error', models.TextField(blank=True, verbose_name='Xatolik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('call_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='requests.callrequest')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='requests.offer')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='requests.servicerequest')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    ]
