# Generated by Django 5.2.17 on 2026-09-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('call_new', 'Yangi chaqiruv'), ('call_status', "Chaqiruv holati o'zgardi"), ('tender_new', 'Yangi tender'), ('offer_new', 'Yangi taklif'), ('offer_accepted', 'Taklif qabul qilindi'), ('offer_declined', 'Taklif rad etildi'), ('service_completed', "Ochiq so'rov yakunlandi"), ('review_new', 'Yangi izoh')], max_length=20, verbose_name='Turi'),
        ),
    ]
