# Generated by Django 5.0.6 on 2026-05-31 13:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=90, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='Ikon (emoji yoki nom)')),
            ],
            options={
                'verbose_name': 'Mutaxassislik',
                'verbose_name_plural': 'Mutaxassisliklar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='Tajriba (yil)')),
                ('clinic_name', models.CharField(blank=True, max_length=150, verbose_name='Klinika nomi')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Kenglik')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Uzunlik')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Shahar')),
                ('district', models.CharField(blank=True, max_length=80, verbose_name='Tuman')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('is_available', models.BooleanField(default=True, verbose_name="Bo'sh (ish qabul qiladi)")),
                ('rating_avg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3, verbose_name="O'rtacha reyting")),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='Izohlar soni')),
                ('accepts_home_visit', models.BooleanField(default=True, verbose_name='Uyga boradi')),
                ('accepts_online', models.BooleanField(default=True, verbose_name='Online konsultatsiya')),
                ('is_top', models.BooleanField(default=False, verbose_name='TOP joylashuv')),
                ('top_until', models.DateTimeField(blank=True, null=True, verbose_name='TOP muddati')),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Hamyon balansi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('specializations', models.ManyToManyField(blank=True, related_name='vets', to='vets.specialization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vet_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Veterinar profili',
                'verbose_name_plural': 'Veterinar profillari',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Xizmat nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Narx')),
                ('duration_min', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='Davomiyligi (daqiqa)')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='vets.vetprofile')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['price'],
            },
        ),
    ]
