# Generated by Django 5.2.17 on 2026-09-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name="Ko'rib chiqilgan"),
        ),
    ]
