# Generated by Django 5.0.6 on 2026-05-31 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        ('vets', '0002_seed_specializations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('home', 'Uyga chaqirish'), ('online', 'Online konsultatsiya'), ('contact', 'Kontakt orqali')], max_length=10, verbose_name='Turi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilindi'), ('on_way', "Yo'lda"), ('completed', 'Yakunlandi'), ('rejected', 'Rad etildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=10, verbose_name='Holat')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Belgilangan vaqt')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Kenglik')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Uzunlik')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('price_agreed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Kelishilgan narx')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.pet')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to='vets.vetprofile')),
            ],
            options={
                'verbose_name': "Chaqiruv (to'g'ridan)",
                'verbose_name_plural': "Chaqiruvlar (to'g'ridan)",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narx')),
                ('can_arrive_at', models.DateTimeField(blank=True, null=True, verbose_name='Qachon kela oladi')),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
                ('status', models.CharField(choices=[('sent', 'Yuborildi'), ('accepted', 'Qabul qilindi'), ('declined', 'Rad etildi'), ('withdrawn', 'Qaytarib olindi')], default='sent', max_length=10, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='vets.vetprofile')),
            ],
            options={
                'verbose_name': 'Taklif',
                'verbose_name_plural': 'Takliflar',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('home', 'Uyga chaqirish'), ('online', 'Online konsultatsiya'), ('contact', 'Kontakt orqali')], max_length=10, verbose_name='Turi')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Shahar')),
                ('district', models.CharField(blank=True, max_length=80, verbose_name='Tuman')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Kenglik')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Uzunlik')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('budget_hint', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Taxminiy byudjet')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('assigned', 'Vet tayinlandi'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi'), ('expired', 'Muddati tugadi')], default='open', max_length=10, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Amal qilish muddati')),
                ('assigned_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='requests.offer')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.pet')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='vets.specialization')),
            ],
            options={
                'verbose_name': "Ochiq so'rov (tender)",
                'verbose_name_plural': "Ochiq so'rovlar (tender)",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='requests.servicerequest'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(fields=('request', 'vet'), name='unique_offer_per_vet'),
        ),
    ]
