# Generated by Django 5.2.17 on 2026-09-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_servicerequest_budget_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan vaqt'),
        ),
        migrations.AddField(
            model_name='callrequest',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Javob berilgan vaqt'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan vaqt'),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilindi'), ('on_way', "Yo'lda"), ('completed', 'Yakunlandi'), ('rejected', 'Rad etildi'), ('cancelled', 'Bekor qilindi'), ('expired', 'Muddati tugadi')], default='pending', max_length=10, verbose_name='Holat'),
        ),
    ]
