# Generated by Django 5.2.17 on 2026-09-19 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_photo_alter_user_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqami noto'g'ri formatda. Namuna: +998901234567", regex='^\\+998\\d{9}$')], verbose_name='Telefon'),
        ),
    ]
