# Generated by Django 5.2.17 on 2026-09-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=80, verbose_name='Viloyat'),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=80, verbose_name='Tuman'),
        ),
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Kenglik'),
        ),
        migrations.AddField(
            model_name='user',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Uzunlik'),
        ),
    ]
