"""Admin panel API marshrutlari (/api/v1/admin/...)."""
from django.urls import path

from .views import (
    AdminCallListView,
    AdminClinicDetailView,
    AdminClinicListCreateView,
    AdminClinicToggleVerifyView,
    AdminLoginView,
    AdminNotificationListView,
    AdminNotificationRetryView,
    AdminReportListView,
    AdminReportResolveView,
    AdminReviewDeleteView,
    AdminReviewListView,
    AdminServiceRequestListView,
    AdminUserDeleteView,
    AdminUserListView,
    AdminUserToggleActiveView,
    AdminVetListView,
    AdminVetSetClinicView,
    AdminVetToggleTopView,
    AdminVetToggleVerifyView,
    AdminVetWalletAdjustView,
    DashboardStatsView,
)

urlpatterns = [
    path("login/", AdminLoginView.as_view(), name="admin-login"),
    path("stats/", DashboardStatsView.as_view(), name="admin-stats"),
    path("users/", AdminUserListView.as_view(), name="admin-users"),
    path("users/<int:pk>/toggle-active/", AdminUserToggleActiveView.as_view(), name="admin-user-toggle"),
    path("users/<int:pk>/", AdminUserDeleteView.as_view(), name="admin-user-delete"),
    path("vets/", AdminVetListView.as_view(), name="admin-vets"),
    path("vets/<int:pk>/toggle-verify/", AdminVetToggleVerifyView.as_view(), name="admin-vet-toggle"),
    path("vets/<int:pk>/toggle-top/", AdminVetToggleTopView.as_view(), name="admin-vet-toggle-top"),
    path("vets/<int:pk>/wallet-adjust/", AdminVetWalletAdjustView.as_view(), name="admin-vet-wallet-adjust"),
    path("vets/<int:pk>/set-clinic/", AdminVetSetClinicView.as_view(), name="admin-vet-set-clinic"),
    path("clinics/", AdminClinicListCreateView.as_view(), name="admin-clinics"),
    path("clinics/<int:pk>/", AdminClinicDetailView.as_view(), name="admin-clinic-detail"),
    path("clinics/<int:pk>/toggle-verify/", AdminClinicToggleVerifyView.as_view(), name="admin-clinic-toggle-verify"),
    path("calls/", AdminCallListView.as_view(), name="admin-calls"),
    path("tenders/", AdminServiceRequestListView.as_view(), name="admin-tenders"),
    path("reviews/", AdminReviewListView.as_view(), name="admin-reviews"),
    path("reviews/<int:pk>/", AdminReviewDeleteView.as_view(), name="admin-review-delete"),
    path("reports/", AdminReportListView.as_view(), name="admin-reports"),
    path("reports/<int:pk>/resolve/", AdminReportResolveView.as_view(), name="admin-report-resolve"),
    path("notifications/", AdminNotificationListView.as_view(), name="admin-notifications"),
    path("notifications/<int:pk>/retry/", AdminNotificationRetryView.as_view(), name="admin-notification-retry"),
]
