# Generated by Django 5.2.17 on 2026-09-19 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
        ('reviews', '0001_initial'),
        ('vets', '0002_seed_specializations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='service_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='requests.servicerequest'),
        ),
        migrations.AlterField(
            model_name='review',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='requests.callrequest'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('request__isnull', False), ('service_request__isnull', True)), models.Q(('request__isnull', True), ('service_request__isnull', False)), _connector='OR'), name='review_exactly_one_source'),
        ),
    ]
