# Generated by Django 5.0.6 on 2026-05-31 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Ism')),
                ('species', models.CharField(help_text='It, mushuk, qush...', max_length=60, verbose_name='Turi')),
                ('breed', models.CharField(blank=True, max_length=80, verbose_name='Zoti')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Yoshi')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', "Urg'ochi"), ('unknown', "Noma'lum")], default='unknown', max_length=10, verbose_name='Jinsi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='Rasm')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hayvon',
                'verbose_name_plural': 'Hayvonlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
