# Generated by Django 5.0.6 on 2026-05-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('call_new', 'Yangi chaqiruv'), ('call_status', "Chaqiruv holati o'zgardi"), ('tender_new', 'Yangi tender'), ('offer_new', 'Yangi taklif'), ('offer_accepted', 'Taklif qabul qilindi'), ('offer_declined', 'Taklif rad etildi'), ('review_new', 'Yangi izoh')], max_length=20, verbose_name='Turi'),
        ),
    ]
